# Generated by Django 5.1.4 on 2025-01-04 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0001_initial'),
        ('epis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaColaboradorEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='colaboradores.colaborador')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='epis.epis')),
            ],
            options={
                'unique_together': {('colaborador', 'epi')},
            },
        ),
    ]
