# Generated by Django 5.1.4 on 2025-01-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='EPI')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('fabricante', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('numero_ca', models.CharField(max_length=20, unique=True, verbose_name='Número do CA')),
                ('arquivo_ca', models.FileField(blank=True, null=True, upload_to='documentos/epis/')),
                ('categoria', models.CharField(choices=[('proteção_cabeça', 'Proteção da Cabeça'), ('proteção_olhos_face', 'Proteção dos Olhos e Face'), ('proteção_auditiva', 'Proteção Auditiva'), ('proteção_respiratoria', 'Proteção Respiratória'), ('proteção_torax', 'Proteção do Tórax'), ('proteção_membros_superiores', 'Proteção dos Membros Superiores'), ('proteção_membros_inferiores', 'Proteção dos Membros Inferiores'), ('proteção_corpo_inteiro', 'Proteção do Corpo Inteiro'), ('proteção_contra_quedas', 'Proteção Contra Quedas')], default='', max_length=50, verbose_name='Categoria')),
                ('validade_ca', models.DateField(verbose_name='Validade do CA')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'EPI',
                'verbose_name_plural': 'EPIs',
            },
        ),
    ]
